import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./App.scss";
import NavBar from "./components/NavBar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="d-flex flex-column min-vh-100">
          <NavBar />
          <main className="flex-grow-1  bg-gradient-my-gradient">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
