import type { Metadata } from "next";
import "./globals.css";
import "./App.scss";

import React from 'react';
import NavBar from "./components/NavBar";
// import { ThemeProvider } from "./context/ThemeContext";
import Footer from "./components/Footer";
import BootstrapClient from "./components/BootstrapClient";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

            <div className="d-flex flex-column min-vh-100">
              <NavBar />
              <main className="flex-grow-1  bg-gradient-my-gradient">
                {children}
              </main>
              <Footer />
            </div>
        <BootstrapClient />
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
